#' Estimate yearly age-specific fertility rates (ASFR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates age-specific fertility rates.
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_min_fert numeric. Lower-bound age of female reproductive period
#' @param age_min_fert numeric. Upper-bound age of female reproductive period
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#'  will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). 
#' @return A data.frame with age-specific fertility rates by year and age.
#' 
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(path = "my_path")
#' # Retrieve age-specific fertility rates
#' asfr <- get_asfr_socsim(opop = opop,
#'                      final_sim_year = 2021, 
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_min_fert = 10,
#'                      age_max_fert = 55,
#'                      age_group = 5)
#' }
#' @export
get_asfr_socsim <- function(opop, final_sim_year, year_min, year_max, year_group = 5, age_min_fert = 15, age_max_fert = 50, age_group = 5) {
  last_month <- max(opop$dob)
  # Year range and breaks
  year_range <- year_min:(year_max-1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  # Age groups of fertility rates
  age_breaks_fert <- seq(age_min_fert, age_max_fert, by = age_group)
  # Calculate year of birth
  opop2 <- opop %>%
    mutate(birth_year = asYr(dob, last_month, final_sim_year))
  # 1. Numerator - births by women of given age group
  numerator <- yearly_birth_by_age_socsim(df = opop2, 
                                          year_range = year_range, 
                                          age_breaks_fert = age_breaks_fert)
  # 2. Denominator - women in reproductive years (1st July)
  denom <- lapply(year_range, get_women_reproductive_age_socsim,
                  df = opop2,
                  final_sim_year = final_sim_year,
                  age_breaks_fert = age_breaks_fert)
  denominator <- data.frame(do.call(rbind, denom))
  # 3. Rate
  asfr <- bind_cols(denominator %>% rename(deno = n),
                    numerator %>% select(nume = n)) %>%
    mutate(socsim = nume/deno,
           year_gr = cut(year, breaks = year_breaks, 
                         include.lowest = F, right = F, ordered_results = T)) %>%
    group_by(year = year_gr, age = agegr) %>%
    summarise(socsim = mean(socsim)) %>%
    ungroup()
  return(asfr)
}