#' Estimate yearly age-specific mortality rates (ASMR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates (yearly) age-specific mortality rates. 
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_max_mort numeric. Maximum age for estimating mortality.
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#' will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). Mortality rates always start from 0 
#' [0,0+age_group). 
#' @return A data.frame with yearly age-specific mortality rates by year and age.
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(path = "my_path")
#' # Retrieve age-specific mortality rates
#' asmr <- get_asmr_socsim(opop = opop,
#'                      final_sim_year = 2021,
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_max_mort = 110,
#'                      age_group = 5)
#' }
#' @export
estimate_mortality_rates <- function(opop, final_sim_year, year_min, year_max, year_group, age_max_mort, age_group) {
  last_month <- max(opop$dob)
  # Year range and breaks 
  year_range <- year_min:(year_max-1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  # Age groups of mortality rates
  if(age_group == 1){
    age_breaks_mort <- c(0, seq(age_group, age_max_mort, by = age_group))
  } else{ 
    age_breaks_mort <- c(0, 1, seq(age_group, age_max_mort, by = age_group))
  }
  # Age levels to complete the census (denominator)
  age_levels_census <- seq(0, age_max_mort-1, by = 1)
  # Calculate age at death and year of death
  opop2 <- opop %>% 
    rename(sex = fem) %>% 
    mutate(age_death_months = ifelse(dod == 0,NA,dod-dob), 
           age_death = trunc(age_death_months/12), 
           age_death_g = cut(age_death, breaks = age_breaks_mort, 
                             include.lowest = F, right = F, ordered_results = T),
           death_year = ifelse(dod == 0, NA, asYr(dod, last_month, final_sim_year)))
  # 1. Numerator - death counts by sex and age
  numerator <- opop2 %>% 
    filter(dod != 0 & death_year %in% year_range & !is.na(age_death_g)) %>%
    count(death_year, sex, age_death_g) %>% 
    rename(year = death_year, age = age_death_g) %>% 
    arrange(year, sex, age) %>% 
    mutate(year = factor(year, levels = year_range),
           sex = factor(sex, levels = c("0","1"))) %>% 
    complete(year, sex, age, fill = list(n = 0))  %>%
    mutate(year = as.numeric(as.character(year)))
  # 2. Denominator - population by sex and age (1st July)
  opop2_subset <- opop2 %>% 
    select(pid, dob, dod, sex)
  yearly_pop_age_sex <- lapply(year_range, census_socsim, 
                               df = opop2_subset, 
                               final_sim_year = final_sim_year,
                               age_levels_census = age_levels_census)  
  denominator <- data.frame(do.call(rbind, yearly_pop_age_sex)) %>% 
    rename(year = census) %>% 
    mutate(age_at_census = as.numeric(as.character(age_at_census)),
           age = cut(age_at_census, breaks = age_breaks_mort, 
                     include.lowest = F, right = F, ordered_results = T)) %>%
    filter(!is.na(age)) %>% 
    group_by(year, sex, age) %>% 
    summarise(n = sum(n)) %>% 
    arrange(year, sex, age) %>% 
    ungroup()
  # 3. Rate
  asmr <- numerator %>% 
    full_join(denominator, by = c("year", "sex", "age"), 
              suffix = c("_num", "_den")) %>% 
    mutate(socsim = n_num / n_den,
           year_gr = cut(year, breaks = year_breaks, 
                         include.lowest = F, right = F, ordered_results = T),
           sex = ifelse(sex == 0, "male", "female")) %>%
    group_by(year = year_gr, sex, age) %>%
    summarise(socsim = mean(socsim)) %>%
    ungroup()
  return(asmr)  
}