#' Estimate yearly age-specific mortality rates (ASMR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates (yearly) age-specific mortality rates. 
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_max_mort numeric. Maximum age for estimating mortality.
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#' will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). Mortality rates always start from 0 
#' [0,0+age_group). 
#' @return A data.frame with yearly age-specific mortality rates by year and age.
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(path = "my_path")
#' # Retrieve age-specific mortality rates
#' asmr <- get_asmr_socsim(opop = opop,
#'                      final_sim_year = 2021,
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_max_mort = 110,
#'                      age_group = 5)
#' }
#' @export
estimate_mortality_rates <- function(opop, final_sim_year, year_min, year_max, year_group, age_max_mort, age_group) {
  last_month <- max(opop$dob)
  # Year range and breaks 
  year_range <- year_min:(year_max-1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  # Age groups of mortality rates
  if(age_group == 1){
    age_breaks_mort <- c(0, seq(age_group, age_max_mort, by = age_group))
  } else{ 
    age_breaks_mort <- c(0, 1, seq(age_group, age_max_mort, by = age_group))
  }
  # Age levels to complete the census (denominator)
  age_levels_census <- seq(0, age_max_mort-1, by = 1)
  # Calculate age at death and year of death
  opop2 <- opop %>% 
    rename(sex = fem) %>% 
    mutate(age_death_months = ifelse(dod == 0,NA,dod-dob), 
           age_death = trunc(age_death_months/12), 
           age_death_g = cut(age_death, breaks = age_breaks_mort, 
                             include.lowest = F, right = F, ordered_results = T),
           death_year = ifelse(dod == 0, NA, asYr(dod, last_month, final_sim_year)))
  # 1. Numerator - death counts by sex and age
  numerator <- opop2 %>% 
    filter(dod != 0 & death_year %in% year_range & !is.na(age_death_g)) %>%
    count(death_year, sex, age_death_g) %>% 
    rename(year = death_year, age = age_death_g) %>% 
    arrange(year, sex, age) %>% 
    mutate(year = factor(year, levels = year_range),
           sex = factor(sex, levels = c("0","1"))) %>% 
    complete(year, sex, age, fill = list(n = 0))  %>%
    mutate(year = as.numeric(as.character(year)))
  # 2. Denominator - population by sex and age (1st July)
  opop2_subset <- opop2 %>% 
    select(pid, dob, dod, sex)
  yearly_pop_age_sex <- lapply(year_range, census_socsim, 
                               df = opop2_subset, 
                               final_sim_year = final_sim_year,
                               age_levels_census = age_levels_census)  
  denominator <- data.frame(do.call(rbind, yearly_pop_age_sex)) %>% 
    rename(year = census) %>% 
    mutate(age_at_census = as.numeric(as.character(age_at_census)),
           age = cut(age_at_census, breaks = age_breaks_mort, 
                     include.lowest = F, right = F, ordered_results = T)) %>%
    filter(!is.na(age)) %>% 
    group_by(year, sex, age) %>% 
    summarise(n = sum(n)) %>% 
    arrange(year, sex, age) %>% 
    ungroup()
  # 3. Rate
  asmr <- numerator %>% 
    full_join(denominator, by = c("year", "sex", "age"), 
              suffix = c("_num", "_den")) %>% 
    mutate(socsim = n_num / n_den,
           year_gr = cut(year, breaks = year_breaks, 
                         include.lowest = F, right = F, ordered_results = T),
           sex = ifelse(sex == 0, "male", "female")) %>%
    group_by(year = year_gr, sex, age) %>%
    summarise(socsim = mean(socsim)) %>%
    ungroup()
  return(asmr)  
}



#' Estimate yearly age-specific fertility rates (ASFR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates age-specific fertility rates.
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_min_fert numeric. Lower-bound age of female reproductive period
#' @param age_min_fert numeric. Upper-bound age of female reproductive period
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#'  will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). 
#' @return A data.frame with age-specific fertility rates by year and age.
#' 
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(path = "my_path")
#' # Retrieve age-specific fertility rates
#' asfr <- get_asfr_socsim(opop = opop,
#'                      final_sim_year = 2021, 
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_min_fert = 10,
#'                      age_max_fert = 55,
#'                      age_group = 5)
#' }
#' @export
estimate_fertility_rates <- function(opop, final_sim_year, year_min, year_max, year_group = 5, age_min_fert = 15, age_max_fert = 50, age_group = 5) {
  last_month <- max(opop$dob)
  # Year range and breaks
  year_range <- year_min:(year_max-1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  # Age groups of fertility rates
  age_breaks_fert <- seq(age_min_fert, age_max_fert, by = age_group)
  # Calculate year of birth
  opop2 <- opop %>%
    mutate(birth_year = asYr(dob, last_month, final_sim_year))
  # 1. Numerator - births by women of given age group
  numerator <- yearly_birth_by_age_socsim(df = opop2, 
                                          year_range = year_range, 
                                          age_breaks_fert = age_breaks_fert)
  # 2. Denominator - women in reproductive years (1st July)
  denom <- lapply(year_range, get_women_reproductive_age_socsim,
                  df = opop2,
                  final_sim_year = final_sim_year,
                  age_breaks_fert = age_breaks_fert)
  denominator <- data.frame(do.call(rbind, denom))
  # 3. Rate
  asfr <- bind_cols(denominator %>% rename(deno = n),
                    numerator %>% select(nume = n)) %>%
    mutate(socsim = nume/deno,
           year_gr = cut(year, breaks = year_breaks, 
                         include.lowest = F, right = F, ordered_results = T)) %>%
    group_by(year = year_gr, age = agegr) %>%
    summarise(socsim = mean(socsim)) %>%
    ungroup()
  return(asfr)
}

###################################################################################
# Utility functions for estimate_fertility_rates and estimate_mortality_rates:
###################################################################################

# Convert SOCSIM months to calendar years. 
asYr <- function(month, last_month, final_sim_year) {
  return(final_sim_year - trunc((last_month - month)/12))
}

## Returns simulation month corresponding to July of a given real calendar year
jul <- function(year, last_month, final_sim_year){
  return((last_month-5) - (final_sim_year - year)*12)
}

## Estimate yearly number of births any given year
yearly_birth_by_age_socsim <- function(df, year_range, age_breaks_fert) {
  
  last_month <- max(df$dob)
  
  out <- df %>% 
    left_join(df %>% select(mom = pid, mother_birth = birth_year), 
              by = "mom") %>% 
    select(birth_year, mother_birth) %>% 
    filter(birth_year %in% year_range) %>% 
    mutate(birth_year_factor = factor(birth_year, levels = year_range),
           mother_age = birth_year - mother_birth,
           mother_agegr_factor = cut(mother_age, breaks = age_breaks_fert, 
                                     include.lowest = F, right = F, ordered_results = T)) %>%
    filter(!is.na(mother_agegr_factor)) %>% 
    count(birth_year = birth_year_factor, mother_agegr = mother_agegr_factor) %>% 
    complete(birth_year, mother_agegr, fill = list(n = 0)) %>% 
    select(year = birth_year, agegr = mother_agegr, n) %>% 
    arrange(year, agegr)
  
  return(out)
  
}

#### Get Women Reproductive Age SOCSIM (Female mid-year population)
# Return women by age alive on the 1st of July of a given year, including right-censored

get_women_reproductive_age_socsim <- function(df, final_sim_year, year, age_breaks_fert) {
  
  last_month <- max(df$dob)
  df$census <- year
  
  out <- df %>% 
    mutate(dod2 = ifelse(dod == 0, 999999999, dod)) %>%
    filter(fem == 1 & dob < jul(year, last_month, final_sim_year) & dod2 >= jul(year, last_month, final_sim_year)) %>%
    mutate(age_at_census = trunc((jul(census, last_month, final_sim_year)-dob)/12),
           agegr_at_census = cut(age_at_census, breaks = age_breaks_fert, 
                                 include.lowest = F, right = F, ordered_results = T)) %>% 
    filter(!is.na(agegr_at_census)) %>% 
    count(agegr_at_census, census) %>% 
    complete(agegr_at_census, census, fill = list(n = 0)) %>% 
    select(year = census, agegr = agegr_at_census, n) %>% 
    arrange(year, agegr)
  
  return(out)
}

## Census SOCSIM (Mid-year population, 1st July)
# Returns population by sex and age alive on the 1st of July of a given year, including right-censored
census_socsim <- function(df, year, final_sim_year, age_levels_census) {
  
  last_month <- max(df$dob)
  df$census <- year 
  
  out <- df %>% 
    mutate(dod2 = ifelse(dod == 0, 999999999, dod)) %>%
    filter(dob < jul(year, last_month, final_sim_year) & dod2 >= jul(year, last_month, final_sim_year)) %>% 
    mutate(age_at_census = trunc((jul(census, last_month, final_sim_year)-dob)/12)) %>%
    count(sex, age_at_census, census) %>% 
    mutate(sex = factor(sex, levels = c("0","1")),
           age_at_census = factor(age_at_census, levels = age_levels_census)) %>%
    complete(sex, age_at_census, census, fill = list(n = 0))
  
  return(out)
}