#' Estimate yearly age-specific mortality rates (ASMR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates (yearly) age-specific mortality rates. 
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_max_mort numeric. Maximum age for estimating mortality.
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#' will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). For `age_group > 1`, mortality rates 
#' are split into an infant group [0,1) and then grouped ages [1, age_group),
#' [age_group, age_group + age_group), and so on.
#' 
#' @importFrom magrittr %>%
#' 
#' @return A data frame with columns `year`, `sex`, `age`, and `socsim`.
#'   `year` is a factor describing the grouped calendar-year interval,
#'   `sex` is `"male"` or `"female"`, `age` is a factor describing the age
#'   interval, and `socsim` is the estimated mortality rate for that cell.
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(fn = "my_path")
#' # Retrieve age-specific mortality rates
#' asmr <- estimate_mortality_rates(opop = opop,
#'                      final_sim_year = 2021,
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_max_mort = 110,
#'                      age_group = 5)
#' }
#' @export
estimate_mortality_rates <- function(opop, final_sim_year, year_min, year_max, year_group, age_max_mort, age_group) {
  last_month <- max(opop$dob)
  year_range <- year_min:(year_max - 1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  if (age_group == 1) {
    age_breaks_mort <- c(0, seq(age_group, age_max_mort, by = age_group))
  } else {
    age_breaks_mort <- c(0, 1, seq(age_group, age_max_mort, by = age_group))
  }
  age_levels_census <- seq(0, age_max_mort - 1, by = 1)
  age_levels_mort <- levels(cut(age_levels_census,
                                breaks = age_breaks_mort,
                                include.lowest = FALSE,
                                right = FALSE,
                                ordered_results = TRUE))

  opop2 <- opop %>%
    rename(sex = fem) %>%
    mutate(age_death_months = ifelse(dod == 0, NA, dod - dob),
           age_death = trunc(age_death_months / 12),
           age_death_g = cut(age_death,
                             breaks = age_breaks_mort,
                             include.lowest = FALSE,
                             right = FALSE,
                             ordered_results = TRUE),
           death_year = ifelse(dod == 0, NA, asYr(dod, last_month, final_sim_year)))

  numerator <- opop2 %>%
    filter(dod != 0 & death_year %in% year_range & !is.na(age_death_g)) %>%
    mutate(age = factor(as.character(age_death_g), levels = age_levels_mort)) %>%
    count(year = death_year, sex, age) %>%
    tidyr::complete(
      year = year_range,
      sex = c(0, 1),
      age = factor(age_levels_mort, levels = age_levels_mort),
      fill = list(n = 0)
    ) %>%
    rename(n_num = n)

  yearly_pop_age_sex <- lapply(year_range, census_socsim,
                               df = opop2 %>% select(pid, dob, dod, sex),
                               final_sim_year = final_sim_year,
                               age_levels_census = age_levels_census)
  denominator <- data.frame(do.call(rbind, yearly_pop_age_sex)) %>%
    rename(year = census) %>%
      mutate(sex = as.numeric(as.character(sex)),
        age_at_census = as.numeric(as.character(age_at_census)),
           age = cut(age_at_census,
                     breaks = age_breaks_mort,
                     include.lowest = FALSE,
                     right = FALSE,
                     ordered_results = TRUE),
           age = factor(as.character(age), levels = age_levels_mort)) %>%
    filter(!is.na(age)) %>%
    group_by(year, sex, age) %>%
    summarise(n_den = sum(n), .groups = "drop")

  numerator %>%
    full_join(denominator, by = c("year", "sex", "age")) %>%
    mutate(n_num = dplyr::coalesce(n_num, 0L),
           n_den = dplyr::coalesce(n_den, 0L),
           year_gr = cut(year,
                         breaks = year_breaks,
                         include.lowest = FALSE,
                         right = FALSE,
                         ordered_results = TRUE)) %>%
    group_by(year = year_gr, sex, age) %>%
    summarise(n_num = sum(n_num),
              n_den = sum(n_den),
              socsim = ifelse(sum(n_den) == 0, NA_real_, sum(n_num) / sum(n_den)),
              .groups = "drop") %>%
    mutate(sex = ifelse(sex == 0, "male", "female")) %>%
    select(year, sex, age, socsim)
}



#' Estimate yearly age-specific fertility rates (ASFR) from a SOCSIM-generated
#'  population file
#' @description Given a population file ('opop') generated by rsocsim, the 
#' function estimates age-specific fertility rates.
#' @param opop An R object from SOCSIM microsimulation output (population file). 
#' @param final_sim_year numeric. Final simulated year in 'real world' time (
#' used to convert 'SOCSIM time' to 'real world' time.)
#' @param year_min numeric. Lower-bound year for which rate should be estimated.
#' @param year_max numeric. Upper-bound year for which rate should be estimated.
#' @param year_group numeric. Size of year groups to estimate rate (year_group=1
#'  will produce single-year estimates)  
#' @param age_min_fert numeric. Lower-bound age of female reproductive period
#' @param age_max_fert numeric. Upper-bound age of female reproductive period
#' @param age_group numeric. Size of age groups to estimate rate (age_group=1
#'  will produce single-age estimates)
#' @details The `final_sim_year` can be obtained from the .sup file and must 
#' refer to to a real-world year.
#' 
#' Grouped year and age ranges (i.e., if `year_group > 1` or `age_group > 1`) 
#' are created as [year;year+year_group). 
#' @return A data frame with columns `year`, `age`, and `socsim`. `year` is a
#'   factor describing the grouped calendar-year interval, `age` is a factor
#'   describing the maternal-age interval, and `socsim` is the estimated
#'   fertility rate for that cell.
#' 
#' @importFrom magrittr %>%
#' 
#'@examples
#' \dontrun{
#' # Read opop file into global environment
#' opop <- read_opop(fn = "my_path")
#' # Retrieve age-specific fertility rates
#' asfr <- estimate_fertility_rates(opop = opop,
#'                      final_sim_year = 2021, 
#'                      year_min = 1750,
#'                      year_max = 2020,
#'                      year_group = 5,
#'                      age_min_fert = 10,
#'                      age_max_fert = 55,
#'                      age_group = 5)
#' }
#' @export
estimate_fertility_rates <- function(opop, final_sim_year, year_min, year_max, year_group = 5, age_min_fert = 15, age_max_fert = 50, age_group = 5) {
  last_month <- max(opop$dob)
  year_range <- year_min:(year_max - 1)
  year_breaks <- seq(year_min, year_max, by = year_group)
  age_breaks_fert <- seq(age_min_fert, age_max_fert, by = age_group)
  opop2 <- opop %>%
    mutate(birth_year = asYr(dob, last_month, final_sim_year))
  numerator <- yearly_birth_by_age_socsim(df = opop2,
                                          year_range = year_range,
                                          age_breaks_fert = age_breaks_fert)
  denom <- lapply(year_range, get_women_reproductive_age_socsim,
                  df = opop2,
                  final_sim_year = final_sim_year,
                  age_breaks_fert = age_breaks_fert)
  denominator <- data.frame(do.call(rbind, denom))

  denominator %>%
    rename(deno = n) %>%
    full_join(numerator %>% rename(nume = n), by = c("year", "agegr")) %>%
    mutate(deno = dplyr::coalesce(deno, 0L),
           nume = dplyr::coalesce(nume, 0L),
           year_gr = cut(year,
                         breaks = year_breaks,
                         include.lowest = FALSE,
                         right = FALSE,
                         ordered_results = TRUE)) %>%
    group_by(year = year_gr, age = agegr) %>%
    summarise(nume = sum(nume),
              deno = sum(deno),
              socsim = ifelse(sum(deno) == 0, NA_real_, sum(nume) / sum(deno)),
              .groups = "drop") %>%
    select(year, age, socsim)
}

###################################################################################
# Utility functions for estimate_fertility_rates and estimate_mortality_rates:
###################################################################################

#' Convert SOCSIM months to calendar years.
#'
#' @param month Simulation month.
#' @param last_month The maximum simulation month recorded in the data.
#' @param final_sim_year Final simulated real world year.
#' @return A numeric vector of the same length as `month`, giving the calendar
#'   year corresponding to each SOCSIM month.
#' @export
asYr <- function(month, last_month, final_sim_year) {
  return(final_sim_year - trunc((last_month - month)/12))
}

#' Get simulation month corresponding to July of a given year.
#'
#' @param year Real calendar year.
#' @param last_month The maximum simulation month present in the data.
#' @param final_sim_year Final simulated real world year.
#' @return A numeric vector of the same length as `year`, giving the SOCSIM
#'   month number corresponding to July in each calendar year.
#' @export
jul <- function(year, last_month, final_sim_year){
  return((last_month-5) - (final_sim_year - year)*12)
}

#' Estimate yearly number of births by mother’s age group in SOCSIM data.
#'
#' @param df Data frame containing SOCSIM population data.
#' @param year_range Vector of years for which births are to be estimated.
#' @param age_breaks_fert Numeric vector of age breakpoints for fertility rate estimation.
#' @return A data frame with columns `year`, `agegr`, and `n`, where `year`
#'   is the calendar year, `agegr` is the maternal age-group factor, and `n`
#'   is the number of births in that cell.
#' @export
yearly_birth_by_age_socsim <- function(df, year_range, age_breaks_fert) {
  age_levels_fert <- levels(cut(seq(min(age_breaks_fert), max(age_breaks_fert) - 1, by = 1),
                                breaks = age_breaks_fert,
                                include.lowest = FALSE,
                                right = FALSE,
                                ordered_results = TRUE))

  out <- df %>%
    left_join(df %>% select(mom = pid, mother_birth = birth_year),
              by = "mom") %>%
    select(birth_year, mother_birth) %>%
    filter(birth_year %in% year_range) %>%
    mutate(birth_year_factor = factor(birth_year, levels = year_range),
           mother_age = birth_year - mother_birth,
           mother_agegr_factor = factor(
             cut(mother_age,
                 breaks = age_breaks_fert,
                 include.lowest = FALSE,
                 right = FALSE,
                 ordered_results = TRUE),
             levels = age_levels_fert
           )) %>%
    filter(!is.na(mother_agegr_factor)) %>%
    count(birth_year = birth_year_factor, mother_agegr = mother_agegr_factor) %>%
    tidyr::complete(birth_year = factor(year_range, levels = year_range),
                    mother_agegr = factor(age_levels_fert, levels = age_levels_fert),
                    fill = list(n = 0)) %>%
    mutate(birth_year = as.numeric(as.character(birth_year))) %>%
    select(year = birth_year, agegr = mother_agegr, n) %>%
    arrange(year, agegr)

  return(out)
}

#' Get women of reproductive age from SOCSIM population data.
#'
#' @description Returns a data frame of women alive on 1st July of the specified year
#' (including right-censored individuals), grouped by age.
#'
#' @param df Data frame containing SOCSIM population data.
#' @param final_sim_year Final simulated real world year.
#' @param year The year for which the census is taken.
#' @param age_breaks_fert Numeric vector of age breakpoints defining the reproductive age groups.
#' @return A data frame with columns `year`, `agegr`, and `n`, where `year`
#'   is the census year, `agegr` is the reproductive-age group factor, and `n`
#'   is the number of women alive in that cell on 1 July.
#' @export
get_women_reproductive_age_socsim <- function(df, final_sim_year, year, age_breaks_fert) {
  last_month <- max(df$dob)
  july_month <- jul(year, last_month, final_sim_year)
  age_levels_fert <- levels(cut(seq(min(age_breaks_fert), max(age_breaks_fert) - 1, by = 1),
                                breaks = age_breaks_fert,
                                include.lowest = FALSE,
                                right = FALSE,
                                ordered_results = TRUE))
  df$census <- year

  out <- df %>%
    mutate(dod2 = ifelse(dod == 0, 999999999, dod)) %>%
    filter(fem == 1 & dob < july_month & dod2 >= july_month) %>%
    mutate(age_at_census = trunc((july_month-dob)/12),
           agegr_at_census = factor(
             cut(age_at_census,
                 breaks = age_breaks_fert,
                 include.lowest = FALSE,
                 right = FALSE,
                 ordered_results = TRUE),
             levels = age_levels_fert
           )) %>%
    filter(!is.na(agegr_at_census)) %>%
    count(agegr_at_census, census) %>%
    tidyr::complete(agegr_at_census = factor(age_levels_fert, levels = age_levels_fert),
                    census = year,
                    fill = list(n = 0)) %>%
    select(year = census, agegr = agegr_at_census, n) %>%
    arrange(year, agegr)

  return(out)
}

#' Census SOCSIM: Population counts by sex and age.
#'
#' @description Returns the population counts by sex and age for individuals alive on 1st July 
#' of the specified year (including right-censored individuals).
#'
#' @param df Data frame containing SOCSIM population data.
#' @param year The census year.
#' @param final_sim_year Final simulated real world year.
#' @param age_levels_census Numeric vector defining age levels for census aggregation.
#' @import dplyr
#' @return A data frame with columns `sex`, `age_at_census`, `census`, and
#'   `n`, giving the number of individuals alive on 1 July in each sex-by-age
#'   cell for the requested census year.
#' @export
census_socsim <- function(df, year, final_sim_year, age_levels_census) {
  last_month <- max(df$dob)
  july_month <- jul(year, last_month, final_sim_year)
  df$census <- year

  out <- df %>%
    mutate(dod2 = ifelse(dod == 0, 999999999, dod)) %>%
    filter(dob < july_month & dod2 >= july_month) %>%
    mutate(age_at_census = trunc((july_month-dob)/12)) %>%
    count(sex, age_at_census, census) %>%
    mutate(sex = factor(sex, levels = c("0","1")),
           age_at_census = factor(age_at_census, levels = age_levels_census)) %>%
    tidyr::complete(sex, age_at_census, census, fill = list(n = 0))

  return(out)
}