#' Create Initial Population for Simulation
#'
#' This function generates an initial population data frame and an empty marriage data frame,
#' then writes them to files in the specified folder. The output filenames are generated by appending
#' ".opop" and ".omar" to the given base name.
#'
#' @param folder A character string specifying the folder where the files will be saved.
#' @param size_opop An integer defining the size of the initial population. Default is 20000.
#' @param output_base A character string for the base name of the output files. Default is "presim".
#'
#' @return None. The function writes two files: one for the initial population and one for empty marriage data.
#'
#' @examples
#' \dontrun{
#' create_initial_population(folder = "C:/simulations", size_opop = 10000, output_base = "simdata")
#' }
#'
#' @export
create_initial_population <- function(folder, size_opop = 20000, output_base = "presim") {
  
  # Construct full file paths for the output files
  output_file_opop <- file.path(folder, paste0(output_base, ".opop"))
  output_file_omar <- file.path(folder, paste0(output_base, ".omar"))
  
  # Create data.frame with 14 columns and nrows = size_opop
  presim_opop <- setNames(
    data.frame(matrix(data = 0, ncol = 14, nrow = size_opop)),
    c("pid", "fem", "group", "nev", "dob", "mom", "pop",
      "nesibm", "nesibp", "lborn", "marid", "mstat", "dod", "fmult")
  )
  
  # Add pid 1:size_opop
  presim_opop$pid <- 1:size_opop
  
  # Add sex randomly
  presim_opop$fem <- sample(0:1, nrow(presim_opop), replace = TRUE)
  
  # Add group 1 for all individuals
  presim_opop$group <- 1
  
  # Add random dates of birth (max age around 50)
  presim_opop$dob <- sample(600:1200, nrow(presim_opop), replace = TRUE)
  
  # Write initial population for pre-simulation (without fertility multiplier)
  write.table(presim_opop, output_file_opop, row.names = FALSE, col.names = FALSE)
  
  # Create an empty data frame for marriage data (presim.omar)
  presim_omar <- data.frame()
  
  # Write empty marriage data for pre-simulation
  write.table(presim_omar, output_file_omar, row.names = FALSE, col.names = FALSE)
}