# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_rsoc_rcpp_hello_world`)
}

timesTwo3 <- function(x) {
    .Call(`_rsoc_timesTwo3`, x)
}

socsimMain <- function() {
    invisible(.Call(`_rsoc_socsimMain`))
}

socsimMain2 <- function() {
    invisible(.Call(`_rsoc_socsimMain2`))
}

