# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

startSocsimWithFile <- function(supfile, seed) {
    .Call('_rsoc_startSocsimWithFile', PACKAGE = 'rsoc', supfile, seed)
}

